kind: pipeline
type: docker
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: irasikhin/standard-version
      username: irasikhin
      password:
        from_secret: docker_password

trigger:
  branch:
    - master

